services:
  - type: web
    name: orakle-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - fromDatabase:
          name: orakle-db
          property: connectionString
        key: DATABASE_URL
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ETH_RPC_URL
        sync: false

databases:
  - name: orakle-db
    plan: free
