# Generated by Django 5.2.4 on 2026-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractanalysis',
            name='contract_address',
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
