# Generated by Django 5.2.4 on 2026-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractanalysis_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractanalysis',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
