# Generated by Django 5.2.4 on 2026-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanatransactionanalysis',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='solanawalletanalysis',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
